/**
 * Cloudflare entry point: the OpenNext worker plus a scheduled keep-alive.
 *
 * Supabase pauses free projects that see no activity for about a week. The cron
 * in wrangler.jsonc calls /api/health every other day, which runs one tiny
 * query, so the database never counts as idle even on a quiet shop site.
 * This file is bundled by wrangler at deploy time (it imports a build output),
 * so it is excluded from the normal TypeScript check.
 */

// @ts-expect-error: generated by `opennextjs-cloudflare build`
import openNext from "./.open-next/worker.js";

// @ts-expect-error: generated by `opennextjs-cloudflare build`
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";

type Env = Record<string, unknown>;
type Context = { waitUntil(promise: Promise<unknown>): void; passThroughOnException(): void };

const worker = {
  fetch: openNext.fetch as (request: Request, env: Env, ctx: Context) => Promise<Response>,

  async scheduled(_controller: unknown, env: Env, ctx: Context) {
    // A failed check throws, so it shows up as a failed run in the Cloudflare dashboard.
    const check = async () => {
      const response = await openNext.fetch(new Request("https://keep-alive.invalid/api/health"), env, ctx);
      if (!response.ok) throw new Error(`Keep-alive check failed: HTTP ${response.status}`);
    };
    ctx.waitUntil(check());
  },
};

export default worker;
